CC = gcc
CFLAGS = -c -Wall -std=c11
LDLIBS = -lm

all: zad1 zad2 zad3 zad4 zad5 zad6 zad7 zad8 zad9

zad1: zad1.o
zad1.o: zad1.c

zad2: zad2.o
zad2.o: zad2.c

zad3: zad3.o
zad3.o: zad3.c

zad4: zad4.o
zad4.o: zad4.c

zad5: zad5.o
zad5.o: zad5.c

zad6: zad6.o
zad6.o: zad6.c

zad7: zad7.o
zad7.o: zad7.c

zad8: zad8.o
zad8.o: zad8.c

zad9: zad9.o
zad9.o: zad9.c

clean:
  rm -f *.o

run1: zad1
  ./zad1
 
run1: zad2
  ./zad2
  
run1: zad3
  ./zad3
  
run1: zad4
  ./zad4
  
run1: zad5
  ./zad5
  
run1: zad6
  ./zad6
  
run1: zad7
  ./zad7
  
run1: zad8
  ./zad8
  
 run1: zad9
  ./zad9
